swagger: "2.0"
info:
  title: Xml Tests
  version: 1.0.0
schemes:
- http
consumes:
- application/xml
- application/json
produces:
- application/xml
- application/json
definitions:
  ModelPlain:
    description: ModelPlain
    type: object
    properties:
      PropertyPlain:
        description: PropertyPlain
        type: string
      PropertyOverridden:
        description: PropertyOverride
        type: string
        xml:
          name: PropertyOverride
  ModelOverridden:
    description: ModelOverride
    type: object
    xml:
      name: ModelOverride
    properties:
      PropertyPlain:
        description: PropertyPlain
        type: string
      PropertyOverridden:
        description: PropertyOverride
        type: string
        xml:
          name: PropertyOverride
  ModelComplex:
    description: ModelComplex
    type: object
    properties:
      PropertyPlain:
        description: PropertyPlain
        $ref: "#/definitions/ModelOverridden"
      PropertyOverridden:
        description: PropertyOverride
        $ref: "#/definitions/ModelOverridden"
        xml:
          name: PropertyOverride