---
directive:
  - from: storage.json
    where: >-
      $.paths["/subscriptions/{subscriptionId}/providers/Microsoft.Storage/checkNameAvailability"].post.description
    set: >-
      Checks that the account name has sufficient cowbell (in order to prevent
      fevers).
    reason: We've experienced a lack of cowbell in storage account names.
  - from: storage.json
    where: >-
      $.paths["/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Storage/storageAccounts/{accountName}"].put.description
    transform: $ += " Make sure you add that extra cowbell."
    reason: Make sure people know.
  - from: storage.json
    where: $.definitions.Usage.description
    transform: return $.toUpperCase()
    reason: >-
      Our new guidelines require upper case descriptions here. Customers love
      it.
  - from: swagger-document
    where: $.paths..operationId
    transform: 'return $.replace(/ies$/, "y")'
    reason: I don't like plural.
  - from: code-model-v1
    where: '$.operations[*]'
    transform: >
      const url = $.methods[0]["url"]; const res =
      url.split("/Microsoft.Storage/")[1].split("/")[0]; $.name.raw = res;
      $.summary = JSON.stringify($, null, 2);
    reason: We wanna group methods by URI.
  - from: swagger-document
    where: $.definitions.*.additionalProperties
    transform: |
      return typeof $ === "boolean"
        ? ($ ? { type: "object" } : undefined)
        : $
    reason: polyfill
input-file:
  - >-
    https://github.com/Azure/azure-rest-api-specs/blob/d374d03801e97737ddb32e01f20513e7b2bbd9c3/arm-storage/2015-06-15/swagger/storage.json
output-artifact:
  - swagger-document.json
  - code-model-v1.yaml
  - pipeline.yaml
  - configuration.yaml
  - source-file-csharp
  - source-file-jsonrpcclient
require: []
use: []
clear-output-folder: {}
use-extension:
  '@microsoft.azure/autorest.csharp': ~2.2.45
  '@microsoft.azure/classic-openapi-validator': ~1.0.9
  '@microsoft.azure/openapi-validator': ~1.0.2
  '@microsoft.azure/autorest.modeler': 2.3.38

no-upgrade-check: {}
skip-upgrade-check: {}
azure-arm: true
azure-validator: true
csharp:
  output-folder: Client
__info: yaml
output-folder: generated
openapi-type: arm
pipeline:
  swagger-document/reflect-api-versions-cs:
    input:
      - identity
      - individual/identity
      - csharp/emitter
    scope: reflect-api-versions
    suffixes: []
  swagger-document/reflect-api-versions-cs/emitter:
    input: reflect-api-versions-cs
    scope: scope-reflect-api-versions-cs-emitter
    suffixes: []
  pipeline-emitter:
    scope: scope-pipeline-emitter
    suffixes:
      - ''
  configuration-emitter:
    scope: scope-configuration-emitter
    suffixes:
      - ''
  swagger-document-override/md-override-loader:
    output-artifact: immediate-config
    scope: perform-load
    suffixes:
      - ''
  swagger-document/loader:
    output-artifact: swagger-document
    scope: perform-load
    suffixes:
      - ''
  swagger-document/individual/transform:
    input: loader
    output-artifact: swagger-document
    suffixes:
      - ''
  swagger-document/individual/schema-validator:
    input: transform
    output-artifact: swagger-document
    suffixes:
      - ''
  swagger-document/individual/identity:
    input: schema-validator
    output-artifact: swagger-document
    suffixes:
      - ''
  swagger-document/compose:
    input: individual/identity
    output-artifact: swagger-document
    suffixes:
      - ''
  swagger-document/transform-immediate:
    input:
      - swagger-document-override/md-override-loader
      - compose
    output-artifact: swagger-document
    suffixes:
      - ''
  swagger-document/transform:
    input: transform-immediate
    output-artifact: swagger-document
    suffixes:
      - ''
  swagger-document/identity:
    input: transform
    output-artifact: swagger-document
    suffixes:
      - ''
  swagger-document/emitter:
    input: identity
    scope: scope-swagger-document/emitter
    suffixes:
      - ''
  openapi-document/openapi-document-converter:
    input: swagger-document/identity
    output-artifact: openapi-document
    suffixes:
      - ''
  openapi-document/transform:
    input: openapi-document-converter
    output-artifact: openapi-document
    suffixes:
      - ''
  openapi-document/identity:
    input: transform
    output-artifact: openapi-document
    suffixes:
      - ''
  openapi-document/emitter:
    input: identity
    scope: scope-openapi-document/emitter
    suffixes:
      - ''
  swagger-document/model-validator:
    input: swagger-document/identity
    scope: model-validator
    suffixes: []
  swagger-document/semantic-validator:
    input: swagger-document/identity
    scope: semantic-validator
    suffixes: []
  csharp/imodeler1:
    input: openapi-document/identity
    output-artifact: code-model-v1
    scope: csharp
    suffixes:
      - ''
  csharp/commonmarker:
    input: imodeler1
    output-artifact: code-model-v1
    suffixes:
      - ''
  csharp/cm/transform:
    input: commonmarker
    output-artifact: code-model-v1
    suffixes:
      - ''
  csharp/cm/emitter:
    input: transform
    scope: scope-cm/emitter
    suffixes:
      - ''
  csharp/generate:
    plugin: csharp
    input: cm/transform
    output-artifact: source-file-csharp
    suffixes:
      - ''
  csharp/simplifier:
    plugin: csharp-simplifier
    input: generate
    output-artifact: source-file-csharp
    suffixes:
      - ''
  csharp/transform:
    input: simplifier
    output-artifact: source-file-csharp
    scope: scope-transform-string
    suffixes:
      - ''
  csharp/emitter:
    input: transform
    scope: scope-csharp/emitter
    suffixes:
      - ''
  jsonrpcclient/imodeler1:
    input: openapi-document/identity
    output-artifact: code-model-v1
    scope: jsonrpcclient
    suffixes: []
  jsonrpcclient/generate:
    plugin: jsonrpcclient
    input: imodeler1
    output-artifact: source-file-jsonrpcclient
    suffixes: []
  jsonrpcclient/transform:
    input: generate
    output-artifact: source-file-jsonrpcclient
    scope: scope-transform-string
    suffixes: []
  jsonrpcclient/emitter:
    input: transform
    scope: scope-jsonrpcclient/emitter
    suffixes: []
  swagger-document/classic-openapi-validator:
    input: swagger-document/identity
    scope: azure-validator-composed
    suffixes:
      - ''
  swagger-document/individual/classic-openapi-validator:
    input: swagger-document/individual/identity
    scope: azure-validator-individual
    suffixes:
      - ''
  swagger-document/openapi-validator:
    input: swagger-document/identity
    scope: azure-validator-composed
    suffixes:
      - ''
  swagger-document/individual/openapi-validator:
    input: swagger-document/individual/identity
    scope: azure-validator-individual
    suffixes:
      - ''
scope-reflect-api-versions-cs-emitter:
  input-artifact: source-file-csharp
  output-uri-expr: $key
scope-pipeline-emitter:
  input-artifact: pipeline
  is-object: true
  output-uri-expr: |
    "pipeline"
scope-configuration-emitter:
  input-artifact: configuration
  is-object: true
  output-uri-expr: |
    "configuration"
perform-load: true
scope-swagger-document/emitter:
  input-artifact: swagger-document
  is-object: true
  output-uri-expr: >
    $config["output-file"] || 

    ($config.namespace ? $config.namespace.replace(/:/g,'_') : undefined) || 

    $config["input-file"][0].split('/').reverse()[0].split('\\').reverse()[0].replace(/\.json$/,
    "")
scope-openapi-document/emitter:
  input-artifact: openapi-document
  is-object: true
  output-uri-expr: >
    $config["output-file"] || 

    ($config.namespace ? $config.namespace.replace(/:/g,'_') : undefined) || 

    $config["input-file"][0].split('/').reverse()[0].split('\\').reverse()[0].replace(/\.json$/,
    "")
scope-cm/emitter:
  input-artifact: code-model-v1
  is-object: true
  output-uri-expr: |
    "code-model-v1"
client-side-validation: true
declare-directive:
  set: '{ transform: `return ${JSON.stringify($)}` }'
  where-operation: |-
    (() => {
      switch ($context.from) {
        case "code-model-v1":
          return { from: "code-model-v1", where: `$.operations[*].methods[?(@.serializedName == ${JSON.stringify($)})]` };
        case "swagger-document":
        default:
          return { from: "swagger-document", where: `$.paths.*[?(@.operationId == ${JSON.stringify($)})]` };
      }
    })()
  where-model: |-
    (() => {
      switch ($context.from) {
        case "code-model-v1":
          throw "not implemented";
        case "swagger-document":
        default:
          return { from: "swagger-document", where: `$.definitions[${JSON.stringify($)}]` };
      }
    })()
  remove-operation: |-
    {
      from: 'swagger-document',
      "where-operation": $,
      transform: 'return undefined'
    }
  rename-operation: |-
    {
      from: 'swagger-document',
      "where-operation": $.from,
      transform: `$.operationId = ${JSON.stringify($.to)}`
    }
  remove-model: |-
    {
      from: 'swagger-document',
      "where-model": $,
      transform: 'return undefined'
    }
  rename-model: |-
    [{
      from: 'swagger-document',
      where: '$.definitions',
      transform: `if ($[${JSON.stringify($.from)}]) { $[${JSON.stringify($.to)}] = $[${JSON.stringify($.from)}]; delete $[${JSON.stringify($.from)}]; }`
    }, {
      from: 'swagger-document',
      where: `$..['$ref']`,
      transform: `$ = $ === "#/definitions/${$.from}" ? "#/definitions/${$.to}" : $`
    }]
  remove-property: |-
    {
      from: 'swagger-document',
      transform: `delete $.properties[${JSON.stringify($)}]`
    }
  rename-property: |-
    {
      from: 'swagger-document',
      transform: `if ($.properties[${JSON.stringify($.from)}]) { $.properties[${JSON.stringify($.to)}] = $.properties[${JSON.stringify($.from)}]; delete $.properties[${JSON.stringify($.from)}]; }`
    }
used-extension:
  - '["@microsoft.azure/autorest.csharp","~2.2.45"]'
  - '["@microsoft.azure/classic-openapi-validator","~1.0.9"]'
  - '["@microsoft.azure/openapi-validator","~1.0.2"]'
  - '["@microsoft.azure/autorest.modeler","2.3.38"]'
scope-csharp/emitter:
  input-artifact: source-file-csharp
scope-jsonrpcclient/emitter:
  input-artifact: source-file-jsonrpcclient
help-content:
  csharp:
    activationScope: csharp
    categoryFriendlyName: 'C# Generator'
    settings:
      - key: azure-arm
        description: generate code in Azure flavor
      - key: fluent
        description: generate code in fluent flavor
      - key: namespace
        description: determines the root namespace to be used in generated code
        type: string
        required: true
      - key: license-header
        description: >-
          text to include as a header comment in generated files (magic strings:
          MICROSOFT_MIT, MICROSOFT_APACHE, MICROSOFT_MIT_NO_VERSION,
          MICROSOFT_APACHE_NO_VERSION, MICROSOFT_MIT_NO_CODEGEN)
        type: string
      - key: payload-flattening-threshold
        description: >-
          max. number of properties in a request body. If the number of
          properties in the request body is less than or equal to this value,
          these properties will be represented as individual method arguments
          instead
        type: number
      - key: add-credentials
        description: >-
          include a credential property and constructor parameter supporting
          different authentication behaviors
      - key: override-client-name
        description: >-
          overrides the name of the client class (usually derived from
          $.info.title)
        type: string
      - key: use-internal-constructors
        description: >-
          generate constructors with internal instead of public visibility
          (useful for convenience layers)
      - key: sync-methods
        description: >-
          determines amount of synchronous wrappers to generate; default:
          essential
        type: '"essential" | "all" | "none"'
      - key: use-datetimeoffset
        description: use DateTimeOffset instead of DateTime to model date/time types
      - key: client-side-validation
        description: >-
          whether to validate parameters at the client side (according to
          OpenAPI definition) before making a request; default: true
        type: boolean
      - key: max-comment-columns
        description: maximum line width of comments before breaking into a new line
        type: number
      - key: output-file
        description: >-
          generate all code into the specified, single file (instead of the
          usual folder structure)
        type: string
      - key: sample-generation
        description: generate sample code from x-ms-examples (experimental)
azure-validator-composed:
  merge-state: composed
azure-validator-individual:
  merge-state: individual
scope-cm-yaml/emitter:
  input-artifact: code-model-v1-yaml
  is-object: true
  output-uri-expr: |
    "code-model-v1-yaml"
scope-transform-string:
  is-object: false
base-folder: .
debug: false
verbose: false
disable-validation: false
__status: {}
